language: go
go:
    - "1.10"
go_import_path: github.com/deadcheat/gonch
before_install:
    - go get -v -u github.com/modocache/gover
    - go get -v -u github.com/mattn/goveralls
    - go get -v -u golang.org/x/tools/cmd/cover
script:
    - go test -coverprofile=gonch.coverprofile
    - $HOME/gopath/bin/gover
    - $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service=travis-ci
